Repository nakiacallaway/alkali-heroes, pull requests merged in 2021-04, with the labels that each got.

#27 Bc 21 import bootstrap approuter.js
  src/routers/AppRouter.js
Labels: bug

#32 feat(component)added individual component
  src/pages/Member.js
Labels: Feature

#44 added alert to confirm new member upon user submit
  src/components/JoinForm.js
Labels: Done

#43 Member page - created basic functionality
  src/App.css
  src/components/MemberCard.js
  src/data/team.js
  src/pages/Member.js
  src/pages/Team.js
  src/routers/AppRouter.js
Labels: Done

#52 Nec 45 jumplinks
  src/App.css
  src/components/Jumplinks.js
  src/data/team.js
  src/pages/Member.js
  src/pages/Team.js
Labels: Done

#64 feat(bug)fixed linkedin links
  src/components/MemberCard.js
Labels: Done

#69 feat(page)added jump link to featured pic
  src/components/MemberCard.js
  src/pages/Dashboard.js
  src/pages/Member.js
Labels: Done
